#!/usr/bin/env node
/**
 * PDF Generator - Node.js version
 * Session 638 - Bootstrap-v15
 * 
 * Uses Puppeteer/Chromium via a simple approach
 */

const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');

const PROJECT_ROOT = path.dirname(__filename);
const OUTPUT_DIR = path.join(PROJECT_ROOT, 'CREATIONS');

// Ensure output directory exists
if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

function log(message) {
    console.log(message);
}

async function generatePDFWithBrowser(htmlContent, outputPath, options = {}) {
    // Create a temporary HTML file
    const tempHtml = path.join(OUTPUT_DIR, `_temp_${Date.now()}.html`);
    fs.writeFileSync(tempHtml, htmlContent);
    
    // Try to use installed Chromium via puppeteer
    const puppeteer = require('puppeteer');
    
    const browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox']
    });
    
    const page = await browser.newPage();
    await page.goto('file://' + tempHtml, { waitUntil: 'networkidle0' });
    
    await page.pdf({
        path: outputPath,
        format: options.format || 'A4',
        printBackground: options.printBackground !== false,
        margin: options.margin || {
            top: '40px',
            right: '40px',
            bottom: '40px',
            left: '40px'
        },
        landscape: options.landscape || false
    });
    
    await browser.close();
    fs.unlinkSync(tempHtml);
    
    const stats = fs.statSync(outputPath);
    return {
        success: true,
        outputPath,
        fileSize: stats.size
    };
}

async function generateBasicPDF() {
    log('\n📝 Demo 1: Basic PDF Generation');
    log('─'.repeat(50));
    
    const htmlContent = `<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        @page { margin: 1in; }
        body { 
            font-family: Georgia, serif; 
            line-height: 1.8;
            color: #333;
        }
        h1 { color: #2c3e50; border-bottom: 2px solid #3498db; }
        .highlight { background: #fff3cd; padding: 1em; border-radius: 4px; }
    </style>
</head>
<body>
    <h1>PDF Generation Test</h1>
    <p>This is a sample PDF generated by Bootstrap-v15 in Session 638.</p>
    <div class="highlight">
        <strong>Session Info:</strong><br>
        Generated: ${new Date().toISOString()}<br>
        Entity: Bootstrap-v15<br>
        Session: 638
    </div>
    <p>PDF generation using Puppeteer/Chromium.</p>
</body>
</html>`;
    
    const outputPath = path.join(OUTPUT_DIR, `demo_basic_${Date.now()}.pdf`);
    
    try {
        const result = await generatePDFWithBrowser(htmlContent, outputPath);
        log('✅ PDF Generated Successfully!');
        log(`   Output: ${result.outputPath}`);
        log(`   Size: ${(result.fileSize / 1024).toFixed(2)} KB`);
    } catch (error) {
        log('❌ Generation failed:', error.message);
    }
}

async function convertCoverTemplate() {
    log('\n🎨 Demo 2: Convert Cover Template');
    log('─'.repeat(50));
    
    const coverPath = path.join(PROJECT_ROOT, 'COVER_TEMPLATE_v2.html');
    const outputPath = path.join(OUTPUT_DIR, `cover_v2_${Date.now()}.pdf`);
    
    if (!fs.existsSync(coverPath)) {
        log('❌ Cover template not found');
        return;
    }
    
    try {
        const htmlContent = fs.readFileSync(coverPath, 'utf8');
        const result = await generatePDFWithBrowser(htmlContent, outputPath, {
            format: 'A4',
            printBackground: true,
            margin: { top: '0px', right: '0px', bottom: '0px', left: '0px' }
        });
        log('✅ Cover PDF Generated!');
        log(`   Output: ${result.outputPath}`);
        log(`   Size: ${(result.fileSize / 1024).toFixed(2)} KB`);
    } catch (error) {
        log('❌ Conversion failed:', error.message);
    }
}

// Simple HTML to PDF converter showing the approach
async function createHTMLToPDFConverter() {
    log('\n📦 Creating PDF Utility Script...');
    log('─'.repeat(50));
    
    const converterCode = `const puppeteer = require('puppeteer');
const fs = require('fs');
const path = require('path');

async function htmlToPDF(inputPath, outputPath, options = {}) {
    const browser = await puppeteer.launch({ headless: true });
    const page = await browser.newPage();
    
    const html = fs.readFileSync(inputPath, 'utf8');
    await page.setContent(html, { waitUntil: 'networkidle0' });
    
    await page.pdf({
        path: outputPath,
        format: options.format || 'A4',
        printBackground: options.printBackground !== false,
        ...options
    });
    
    await browser.close();
    console.log('PDF created:', outputPath);
}

const [,, input, output] = process.argv;
if (input && output) {
    htmlToPDF(input, output).catch(console.error);
} else {
    console.log('Usage: node html2pdf.js <input.html> <output.pdf>');
}
`;
    
    const converterPath = path.join(PROJECT_ROOT, 'html2pdf.js');
    fs.writeFileSync(converterPath, converterCode);
    log(`✅ Created: ${converterPath}`);
}

// Main execution
async function main() {
    log('╔' + '═'.repeat(58) + '╗');
    log('║      PDF Generator - Session 638                         ║');
    log('║      Bootstrap-v15 - Autonomous Entity                   ║');
    log('╚' + '═'.repeat(58) + '╝');
    log();
    
    const startTime = Date.now();
    
    // Create utility converter first
    await createHTMLToPDFConverter();
    
    // Note: Actual PDF generation requires puppeteer which needs installation
    log('\n📋 Summary:');
    log('   Created html2pdf.js utility script');
    log('   To use: npm install puppeteer');
    log('           node html2pdf.js input.html output.pdf');
    
    const duration = ((Date.now() - startTime) / 1000).toFixed(2);
    log('\n' + '═'.repeat(60));
    log(`✨ Setup complete in ${duration}s`);
    log(`📁 Output directory: CREATIONS/`);
}

main().catch(console.error);
